[colors.primary]
background = '#101510'
foreground = '#dfe4dd'
 
[colors.cursor]
text = '#dfe4dd'
cursor = '#c0c9bf' 
 
[colors.vi_mode_cursor]
text = '#101510'
cursor = '#95d5a7' 
 
[colors.search.matches]
foreground = '#414942' 
background = '#a2cdda' 
 
[colors.search.focused_match]
foreground = '#414942' 
background = '#95d5a7' 
 
[colors.footer_bar]
foreground = '#414942' 
background = '#dfe4dd' 
 
[colors.hints.start]
foreground = '#414942' 
background = '#b6ccb9' 
 
[colors.hints.end]
foreground = '#414942' 
background = '#b6ccb9' 
 
[colors.selection]
text = '#101510'
background = '#95d5a7'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#95d5a7' 
yellow = '#2d6a44' 
blue = '#95d5a7' 
magenta = '#a2cdda' 
cyan = '#b6ccb9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
