##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, match:class (.*)

#   *********  Identifying window class: hyprctl clients***********

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, match:class (.*)
windowrule = opacity 1.0, match:class (darktable|gimp|brave.browser|librewolf|ristretto)

# Fix some dragging issues with XWayland
windowrulev2 = nofocus, match:class ^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Floating windows
windowrulev2 = center, tag:floating-window

#windowrule = tag +floating-window, class:(xdg-desktop-portal-gtk|sublime_text|DesktopEditors), title:^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files)
windowrule = match:title ^(Renomear ".*"|Open File|Open|Save|Save As|Export|Import|Choose File|Rename), match:class ^(.*)$, float on, stay_focused on
windowrule = match:title ^(Renomear ".*"|Copear ".*"|Colar ".*"|Progresso da operação do ficheiro), match:class ^(.*)$, float on, stay_focused on
windowrule = match:class (org.keepassxc.KeePassXC), float on
windowrule = size 1000 600, match:class (org.keepassxc.KeePassXC)
windowrule = match:class (xdg-desktop-portal-hyprland), float on
windowrule = match:class (Xdg-desktop-portal-gtk), float on
windowrulev2 = noborder, match:class (Xdg-desktop-portal-gtk)
windowrule = match:class (org.gnome.Calculator), float on
windowrule = match:class (org.pulseaudio.pavucontrol), float on
windowrule = size 1000 600, match:class (org.pulseaudio.pavucontrol)
windowrule = match:class org.gnome.DiskUtility, match:title Discos, float on
windowrule = match:class nwg-look, match:title nwg-look, float on
windowrulev2 = size 1000 600, match:class nwg-look, match:title nwg-look

#rofi
layerrulev2 = dim_around, rofi
layerrulev2 = animation popin 80%, rofi

#Blur Waybar
#layerrule = blur, waybar
#layerrule = ignorezero, Waybar
#layerrule = ignorealpha 0.5, waybar
