##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

#   *********  Identifying window class: hyprctl clients***********

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, match:class .*
windowrule = opacity 1.0, match:class (darktable|gimp|brave.browser|librewolf|ristretto)

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Floating windows
#windowrulev2 = center, tag:floating-window

windowrule = match:title ^(Renomear ".*"|Open File|Open|Save|Save As|Export|Import|Choose File|Rename), match:class ^(.*)$, float on, stay_focused on
windowrule = match:title ^(Renomear ".*"|Copear ".*"|Colar ".*"|Progresso da operação do ficheiro), match:class ^(.*)$, float on, stay_focused on
windowrule = match:class (org.keepassxc.KeePassXC|org.gnome.Calculator|org.gnome.DiskUtility|nwg-look|pavucontrol|org.gnome.Calendar|org.gnome.clocks|io.missioncenter.MissionCenter), float on
windowrule = match:class (Xdg-desktop-portal-hyprland|xdg-desktop-portal-hyprland), float on, stay_focused on
windowrule = match:class (Xdg-desktop-portal-gtk|xdg-desktop-portal-gtk), float on, stay_focused on
windowrule = size 1100 700, match:class (org.gnome.Calendar|pavucontrol|nwg-look|org.keepassxc.KeePassXC|org.gnome.clocks|io.missioncenter.MissionCenter)

#rofi
#layerrulev2 = dim_around, rofi
#layerrulev2 = animation popin 80%, rofi

#Blur Waybar
#layerrule = blur, waybar
#layerrule = ignorezero, Waybar
#layerrule = ignorealpha 0.5, waybar
